/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/cf1ca89b-fef5-42c3-9ed9-7e09c68d88c8 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String username;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define BUTTON_A 0

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

bool waitResponse = false;
void loop() {
  ArduinoCloud.update();
  // Your code here 
  if(!digitalRead(BUTTON_A)){
    username = "What's your name?";
    ArduinoCloud.update();
    Serial.println(username);
    while(waitResponse){ delay(100); }
    username = "Hello " + username;
    ArduinoCloud.update();
    Serial.println(username);
    waitResponse = false;
    delay(1000);
  }
  
}



/*
  Since Username is READ_WRITE variable, onUsernameChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onUsernameChange()  {
  // Add your code here to act upon Username change
  Serial.println(username);
  waitResponse = true;
  delay(100);

}